[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/amber"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/gemstones"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/precious-semi-precious-gemstones"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/education"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/gem-guide"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/certificates"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/custom-bracelet"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/build-your-set"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/prayer-beads"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/collections"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/bespoke"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
